# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screen4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 440)
        Dialog.setStyleSheet("background-color: #010102")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scoresLabel = QtWidgets.QLabel(Dialog)
        self.scoresLabel.setMaximumSize(QtCore.QSize(99, 26))
        self.scoresLabel.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: 30pt \"Wide Latin\";")
        self.scoresLabel.setScaledContents(False)
        self.scoresLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scoresLabel.setOpenExternalLinks(False)
        self.scoresLabel.setObjectName("scoresLabel")
        self.gridLayout_2.addWidget(self.scoresLabel, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:15px;\n"
"    padding:10px 11px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.menuButton.setObjectName("menuButton")
        self.verticalLayout_2.addWidget(self.menuButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 0, 5, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scoresLabel.setText(_translate("Dialog", "HELP"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>* instruction 1<br/>* instruction 2</p></body></html>"))
        self.menuButton.setText(_translate("Dialog", "<"))
# import imgs_rc
