# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 441)
        self.bgLabel = QtWidgets.QLabel(MainWindow)
        self.bgLabel.setGeometry(QtCore.QRect(0, 0, 591, 441))
        self.bgLabel.setStyleSheet("")
        self.bgLabel.setText("")
        self.bgLabel.setObjectName("bgLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 200, 501, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playNowButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playNowButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:30px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.playNowButton.setObjectName("playNowButton")
        self.horizontalLayout.addWidget(self.playNowButton)
        self.helpButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.helpButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:30px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.playNowButton.setText(_translate("MainWindow", "Play Now"))
        self.helpButton.setText(_translate("MainWindow", "GUIDE"))
