# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screen3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 440)
        Dialog.setStyleSheet("background-color: #010102")
        self.scoresLabel = QtWidgets.QLabel(Dialog)
        self.scoresLabel.setGeometry(QtCore.QRect(11, 20, 61, 26))
        self.scoresLabel.setMaximumSize(QtCore.QSize(99, 26))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.scoresLabel.setFont(font)
        self.scoresLabel.setStyleSheet("color:  #c123de;\n"
"font:  \"Wide Latin\";")
        self.scoresLabel.setScaledContents(False)
        self.scoresLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scoresLabel.setOpenExternalLinks(False)
        self.scoresLabel.setObjectName("scoresLabel")
        self.scoreLabel = QtWidgets.QLabel(Dialog)
        self.scoreLabel.setGeometry(QtCore.QRect(70, 10, 141, 44))
        self.scoreLabel.setMaximumSize(QtCore.QSize(16777215, 135))
        self.scoreLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:  #c123de;\n"
"font: 20pt ;\n"
"border-radius:10px;\n"
"padding:2px 2px;")
        self.scoreLabel.setObjectName("scoreLabel")
        self.menuButton = QtWidgets.QPushButton(Dialog)
        self.menuButton.setGeometry(QtCore.QRect(522, 14, 66, 38))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:15px;\n"
"    padding:10px 11px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.menuButton.setObjectName("menuButton")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(120, 140, 367, 192))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: #c123de;\n"
"border-radius:10px;\n"
"padding:2px 2px;\n"
"color: white;")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkAnswerButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.checkAnswerButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:20px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.checkAnswerButton.setObjectName("checkAnswerButton")
        self.verticalLayout_8.addWidget(self.checkAnswerButton)
        self.gridLayout.addLayout(self.verticalLayout_8, 2, 0, 1, 1)
        self.questionLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.questionLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.questionLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.questionLabel.setStyleSheet("color: white;\n"
"font: 30pt \"MS Shell Dlg 2\";")
        self.questionLabel.setLineWidth(1)
        self.questionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scoresLabel.setText(_translate("Dialog", "SCORES"))
        self.scoreLabel.setText(_translate("Dialog", "0"))
        self.menuButton.setText(_translate("Dialog", "MENU"))
        self.checkAnswerButton.setText(_translate("Dialog", "CHECK"))
        self.questionLabel.setText(_translate("Dialog", "QUESTION"))
