# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 444)
        Dialog.setStyleSheet("")
        self.bgLabel = QtWidgets.QLabel(Dialog)
        self.bgLabel.setGeometry(QtCore.QRect(0, -100, 601, 651))
        self.bgLabel.setStyleSheet("")
        self.bgLabel.setText("")
        self.bgLabel.setObjectName("bgLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 40, 214, 351))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.easyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.easyButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:30px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.easyButton.setObjectName("easyButton")
        self.verticalLayout.addWidget(self.easyButton)
        self.normalButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.normalButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:30px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.normalButton.setObjectName("normalButton")
        self.verticalLayout.addWidget(self.normalButton)
        self.mediumButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mediumButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:30px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.mediumButton.setObjectName("mediumButton")
        self.verticalLayout.addWidget(self.mediumButton)
        self.hardButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.hardButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:30px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.hardButton.setObjectName("hardButton")
        self.verticalLayout.addWidget(self.hardButton)
        self.menuButton = QtWidgets.QPushButton(Dialog)
        self.menuButton.setGeometry(QtCore.QRect(20, 10, 66, 38))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:15px;\n"
"    padding:10px 11px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.menuButton.setObjectName("menuButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.easyButton.setText(_translate("Dialog", "EASY"))
        self.normalButton.setText(_translate("Dialog", "NORMAL"))
        self.mediumButton.setText(_translate("Dialog", "MEDIUM"))
        self.hardButton.setText(_translate("Dialog", "HARD"))
        self.menuButton.setText(_translate("Dialog", "<"))
# import imgs_rc
