# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screen4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 440)
        Dialog.setStyleSheet("background-color: #010102")
        self.helpLabel = QtWidgets.QLabel(Dialog)
        self.helpLabel.setGeometry(QtCore.QRect(115, 11, 371, 56))
        self.helpLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.helpLabel.setMaximumSize(QtCore.QSize(700, 56))
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.helpLabel.setFont(font)
        self.helpLabel.setStyleSheet("color: #c123de;\n"
"font: 30pt \"Wide Latin\";")
        self.helpLabel.setLineWidth(0)
        self.helpLabel.setMidLineWidth(0)
        self.helpLabel.setScaledContents(False)
        self.helpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLabel.setOpenExternalLinks(False)
        self.helpLabel.setObjectName("helpLabel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(11, 120, 577, 280))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.menuButton = QtWidgets.QPushButton(Dialog)
        self.menuButton.setGeometry(QtCore.QRect(11, 20, 61, 38))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:15px;\n"
"    padding:10px 11px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.menuButton.setObjectName("menuButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.helpLabel.setText(_translate("Dialog", "GUIDE"))
        self.label.setText(_translate("Dialog", "<html>\n"
"  <head></head>\n"
"  <body>\n"
"    <ul>\n"
"      <li>1 - The score you have earned so far will be<br>displayed in the label located at the top left cornerr</li><br>\n"
"      <li>2 - Ready for a challenge? Solve the math problem<br> in the purple box using only numbers. Show us what you\'ve got!</li><br>\n"
"      <li>3 - Let\'s see if you\'re right! Hit the \"CHECK\" button<br> and find out! </li>\n"
"    </ul>\n"
"  </body>\n"
"</html>"))
        self.menuButton.setText(_translate("Dialog", "<"))
import imgs_rc
