# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screen3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 440)
        Dialog.setStyleSheet("background-color: #010102")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 4, 1, 1)
        self.scoresLabel = QtWidgets.QLabel(Dialog)
        self.scoresLabel.setMaximumSize(QtCore.QSize(99, 26))
        self.scoresLabel.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: 8pt \"Wide Latin\";")
        self.scoresLabel.setScaledContents(False)
        self.scoresLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scoresLabel.setOpenExternalLinks(False)
        self.scoresLabel.setObjectName("scoresLabel")
        self.gridLayout.addWidget(self.scoresLabel, 0, 0, 1, 1)
        self.answerLabel = QtWidgets.QLabel(Dialog)
        self.answerLabel.setObjectName("answerLabel")
        self.gridLayout.addWidget(self.answerLabel, 5, 2, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 0, 5, 1, 1)
        self.scoreLabel = QtWidgets.QLabel(Dialog)
        self.scoreLabel.setMaximumSize(QtCore.QSize(16777215, 135))
        self.scoreLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(170, 85, 255);\n"
"font: 20pt ;\n"
"border-radius:10px;\n"
"padding:2px 2px;")
        self.scoreLabel.setObjectName("scoreLabel")
        self.gridLayout.addWidget(self.scoreLabel, 0, 1, 1, 2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkAnswerButton = QtWidgets.QPushButton(Dialog)
        self.checkAnswerButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:20px;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.checkAnswerButton.setObjectName("checkAnswerButton")
        self.verticalLayout_8.addWidget(self.checkAnswerButton)
        self.gridLayout.addLayout(self.verticalLayout_8, 6, 3, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout.addLayout(self.verticalLayout_7, 6, 4, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout.addLayout(self.verticalLayout_4, 6, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("background:linear-gradient(to bottom, #c123de 5%, #a20dbd 100%);\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#c123de;\n"
"    font-family:Verdana;\n"
"    font-size:15px;\n"
"    padding:10px 11px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 11px #9b14b3;")
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout.addWidget(self.menuButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 6, 1, 1)
        self.questionLabel = QtWidgets.QLabel(Dialog)
        self.questionLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.questionLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.questionLabel.setStyleSheet("color: white;\n"
"font: 30pt \"MS Shell Dlg 2\";")
        self.questionLabel.setLineWidth(1)
        self.questionLabel.setText("")
        self.questionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 2, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scoresLabel.setText(_translate("Dialog", "SCORES"))
        self.answerLabel.setText(_translate("Dialog", "TextLabel"))
        self.scoreLabel.setText(_translate("Dialog", "0"))
        self.checkAnswerButton.setText(_translate("Dialog", "CHECK"))
        self.menuButton.setText(_translate("Dialog", "MENU"))
# import imgs_rc
